// Generates src/components/Icon/icons.generated.ts from the SVG files in
// src/components/Icon/svg/{16,24}/ and their Figma sources in svg/sources.json.
// Run: npm run build:icons  (after adding or replacing an SVG)
//
// SVG rules: exported from Figma, primary color replaced with currentColor,
// no width/height on <svg> (size comes from CSS).
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';

const dir = 'src/components/Icon/svg';
const sources = JSON.parse(readFileSync(`${dir}/sources.json`, 'utf8'));
const svgRe = /^<svg[^>]*viewBox="([^"]+)"[^>]*>([\s\S]*)<\/svg>\s*$/;

const sets = {};
for (const size of ['16', '24']) {
  sets[size] = {};
  const files = readdirSync(`${dir}/${size}`).filter((f) => f.endsWith('.svg')).sort();
  for (const file of files) {
    const name = file.slice(0, -4);
    const m = svgRe.exec(readFileSync(`${dir}/${size}/${file}`, 'utf8').trim());
    if (!m) throw new Error(`${size}/${file}: expected a single <svg> with a viewBox`);
    const source = sources[size]?.[name];
    if (!source) throw new Error(`${size}/${file}: add it to svg/sources.json`);
    sets[size][name] = { viewBox: m[1], body: m[2].replace(/\s*\n\s*/g, ''), ...source };
  }
}

const literal = (names) => names.map((n) => `'${n}'`).join(' | ');
const ts = [
  '// Auto-generated by build-icons.js — do not edit. Source: src/components/Icon/svg/',
  '',
  'export interface IconDef {',
  '  viewBox: string;',
  '  /** Inner SVG markup; the primary color is `currentColor`. */',
  '  body: string;',
  '  /** Figma frame the icon lives in. */',
  '  group: string;',
  '  /** Figma variant / layer name. */',
  '  figma: string;',
  '  /** Figma node id of the Color=Primary variant. */',
  '  node: string;',
  '  /** Figma node id of the parent frame (for links). */',
  '  frame: string;',
  '}',
  '',
  `export type Icon16Name = ${literal(Object.keys(sets['16']))};`,
  `export type Icon24Name = ${literal(Object.keys(sets['24']))};`,
  '',
  `export const ICONS_16: Record<Icon16Name, IconDef> = ${JSON.stringify(sets['16'], null, 2)};`,
  '',
  `export const ICONS_24: Record<Icon24Name, IconDef> = ${JSON.stringify(sets['24'], null, 2)};`,
  '',
].join('\n');

writeFileSync('src/components/Icon/icons.generated.ts', ts);
console.log(`Built ${Object.keys(sets['16']).length} 16px + ${Object.keys(sets['24']).length} 24px icons`);
