// Generates src/tokens/build/tokens.css and tokens.js from src/tokens/tokens.json.
// Run: npm run build:tokens
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const tokens = JSON.parse(readFileSync('src/tokens/tokens.json', 'utf8'));
const flat = [];
for (const [group, entries] of Object.entries(tokens)) {
  for (const [name, { value, source }] of Object.entries(entries)) {
    flat.push({ name: `--${group}-${name}`, group, value, source });
  }
}

mkdirSync('src/tokens/build', { recursive: true });
const css = [
  '/* Auto-generated by build-tokens.js — do not edit. Source: src/tokens/tokens.json */',
  ':root {',
  ...flat.map((t) => `  ${t.name}: ${t.value}; /* ${t.source} */`),
  '}',
  '',
].join('\n');
writeFileSync('src/tokens/build/tokens.css', css);
writeFileSync(
  'src/tokens/build/tokens.js',
  `// Auto-generated by build-tokens.js — do not edit.\nexport const tokens = ${JSON.stringify(flat, null, 2)};\n`,
);
console.log(`Built ${flat.length} tokens`);
