// Generates src/tokens/build/tokens.css and tokens.js from src/tokens/tokens.json.
// Run: npm run build:tokens
//
// A token is { value, source } and may also have:
//   dark  — value for the dark theme (written under [data-theme="dark"])
// A value can reference another token as "{group.name}" — it becomes var(--group-name) in CSS.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const tokens = JSON.parse(readFileSync('src/tokens/tokens.json', 'utf8'));

const ref = /^\{([\w-]+)\.([\w-]+)\}$/;
const lookup = (group, name) => {
  const t = tokens[group]?.[name];
  if (!t) throw new Error(`Unknown token reference {${group}.${name}}`);
  return t;
};
// Raw value for docs (references resolved), CSS value (references as var()).
const resolve = (value) => {
  const m = ref.exec(value);
  return m ? resolve(lookup(m[1], m[2]).value) : value;
};
const toCss = (value) => {
  const m = ref.exec(value);
  return m ? `var(--${m[1]}-${m[2]})` : value;
};

const flat = [];
for (const [group, entries] of Object.entries(tokens)) {
  for (const [name, { value, dark, source }] of Object.entries(entries)) {
    flat.push({
      name: `--${group}-${name}`,
      group,
      value: resolve(value),
      css: toCss(value),
      ...(ref.test(value) && { ref: value }),
      ...(dark !== undefined && { dark: resolve(dark), darkCss: toCss(dark), ...(ref.test(dark) && { darkRef: dark }) }),
      source,
    });
  }
}

const themed = flat.filter((t) => t.dark !== undefined);
const line = (name, css, comment) => `  ${name}: ${css}; /* ${comment} */`;

mkdirSync('src/tokens/build', { recursive: true });
const css = [
  '/* Auto-generated by build-tokens.js — do not edit. Source: src/tokens/tokens.json */',
  ':root {',
  ...flat.map((t) => line(t.name, t.css, t.source)),
  '}',
  '',
  '/* Light theme is the default; repeated here so a light block can sit inside a dark one. */',
  '[data-theme="light"] {',
  ...themed.map((t) => line(t.name, t.css, 'light')),
  '}',
  '',
  '[data-theme="dark"] {',
  ...themed.map((t) => line(t.name, t.darkCss, 'dark')),
  '}',
  '',
].join('\n');
writeFileSync('src/tokens/build/tokens.css', css);

const js = flat.map(({ css: _css, darkCss: _darkCss, ...t }) => t);
writeFileSync(
  'src/tokens/build/tokens.js',
  `// Auto-generated by build-tokens.js — do not edit.\nexport const tokens = ${JSON.stringify(js, null, 2)};\n`,
);
console.log(`Built ${flat.length} tokens (${themed.length} themed)`);
